### PR TITLE
Added missing language items (2.1)

### PR DESCRIPTION
**Pull request by jacboy**
http://codequake.de/forum/index.php/Thread/2674/

### CODE REVIEW

**Comment by jacboy** [comment]
@ray176 Das hier entspricht der Änderung im 2.0er-Branch, bitte auch noch mergen :-)

**Comment by ray176** [comment]
No, the changes will be part of the next merge commit :smiley:

**Comment by jacboy** [comment]
Okay, so I´am not allowed to delete my own fork of the Fireball packages to prevent loosing this information?

**Comment by ray176** [comment]
Feel free to do with your fork what you want. Your changes were merged into our repository, the rest does not affect you anymore.

**Comment by jacboy** [comment]
Okay thanks.

**Pull request closed without merging**
